//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aluno
    {
        public int RA { get; set; }
        public string Senha { get; set; }
        public string Nome { get; set; }
        public string Curso { get; set; }
    
        public virtual Pessoa Pessoa { get; set; }
    }
}
