//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Evento()
        {
            this.Palestrante = new HashSet<Palestrante>();
            this.Participante = new HashSet<Participante>();
        }
    
        public int Id { get; set; }
        public int Criador { get; set; }
        public bool Cancelado { get; set; }
        public string Local { get; set; }
        public System.DateTime Data { get; set; }
        public string Descricao { get; set; }
        public bool Palestra { get; set; }
        public bool Reuniao { get; set; }
        public bool Privado { get; set; }
        public int Tempo { get; set; }
        public bool Aprovada { get; set; }
    
        public virtual Pessoa Pessoa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Palestrante> Palestrante { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Participante> Participante { get; set; }
    }
}
