//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Participante
    {
        public int Id_pessoa { get; set; }
        public int Id_reuniao { get; set; }
        public bool confirmacao { get; set; }
    
        public virtual Pessoa Pessoa { get; set; }
        public virtual Reuniao Reuniao { get; set; }
    }
}
