//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pessoa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pessoa()
        {
            this.Evento = new HashSet<Evento>();
            this.Palestrante1 = new HashSet<Palestrante>();
            this.Participante = new HashSet<Participante>();
        }
    
        public int Identificacao { get; set; }
        public string Nome { get; set; }
        public string Senha { get; set; }
        public string Grupo { get; set; }
        public string Curso { get; set; }
        public string Departamento { get; set; }
        public string Email { get; set; }
        public Nullable<bool> Adm { get; set; }
        public Nullable<bool> Palestrante { get; set; }
        public Nullable<bool> Organizador { get; set; }
    
        public virtual Certificado Certificado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Evento> Evento { get; set; }
        public virtual Horario Horario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Palestrante> Palestrante1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Participante> Participante { get; set; }
    }
}
